### ISSUE TITLE
Add Hercules support

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/Fit2Obs#15]
The new MSU partition Hercules has come online. Add support for Hercules.

See https://github.com/NOAA-EMC/global-workflow/issues/1588 for more details.

**Comment by DavidHuber-NOAA** [comment]
Based on a review by @jack-woollen, the Orion-built executable appears to work properly on Hercules.  It will be worth it to port Fit2Obs to Hercules at some point (i.e. at Orion end of life), but this will require porting to spack-stack/Intel 2023+ as well and doesn't appear necessary at this point.  Thus, I recommend shelving this issue for the time being.
