### ISSUE TITLE
Update Jet spack-stack path to new contrib location

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/Fit2Obs#26]
All codes on Jet must move away from `lfs4` filesystem. The spack-stack team have made a new install of spack-stack/1.6.0 under `/contrib` on Jet to avoid future filesystem issues like what has happened on `lfs4`.

Update the Jet modulefile to point to new location: `/contrib/spack-stack/spack-stack-1.6.0/envs/gsi-addon-intel/install/modulefiles/Core`

Related to https://github.com/NOAA-EMC/global-workflow/issues/2841

**Comment by KateFriedman-NOAA** [comment]
Successfully tested build on Jet with new `/contrib` location for `spack-stack/1.6.0` install.

**Comment by KateFriedman-NOAA** [comment]
Have installed new `wxflow.1.1.3` tag on Jet, Hera, and WCOSS2. @WalterKolczynski-NOAA please install on Orion, thanks!

```
git clone -b wflow.1.1.3 https://github.com/NOAA-EMC/Fit2Obs.git ./v1.1.3
cd v1.1.3
INSTALL_PREFIX=location_of_install ./ush/build.sh
```

**Comment by WalterKolczynski-NOAA** [comment]
Done

**Comment by KateFriedman-NOAA** [comment]
Thanks @WalterKolczynski-NOAA !
