### ISSUE TITLE
Setup Fit2Obs to compile and run C96_atm3DVar CI test on Gaea-C5

### ISSUE THREAD

**Issue by DavidBurrows-NCO** [NOAA-EMC/Fit2Obs#28]
Update build files and add Gaea-specific module files to compile and run Fit2Obs for C96_atm3DVar global-workflow CI experiment on Gaea-C5

**Comment by KateFriedman-NOAA** [comment]
Tag `wflow.1.1.4` cut: https://github.com/NOAA-EMC/Fit2Obs/releases/tag/wflow.1.1.4

@WalterKolczynski-NOAA please install on MSU. I will install elsewhere.

**Comment by KateFriedman-NOAA** [comment]
Installed the new `wflow.1.1.4` tag on WCOSS2, Hera, and Jet.
