### ISSUE TITLE
Fix fit2obs to run with updated global-workflow

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/Fit2Obs#4]
The fit2obs does not work within global-workflow anymore due to script updates in global-workflow (e.g. standardization and require bash).  Change scripts to bash and test fit2obs on WCOSS2 within global-workflow develop. Just get it working again, don't dive into additional changes at this time.

**Comment by KateFriedman-NOAA** [comment]
Made fork of fit2obs and new branch for updates: https://github.com/KateFriedman-NOAA/Fit2Obs/tree/feature/wcoss2_jet_support

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA FYI for the a5782e9 commit, which is a matching change to one done on the workflow side: https://github.com/NOAA-EMC/global-workflow/issues/1232#issuecomment-1450522359

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA FYI, the fit2obs build was cmake'd by @aerorahul and my branch ingested those updates and completed some necessary updates related to it (8a717c6).

I have also made significant updates in my global-workflow branch to pull fit2obs out of the vrfy job, make it a standalone job, and update it to work with my fit2obs branch (including updated build). I am testing these updates on Hera and Orion (going well so far). I will test on WCOSS2 once it looks good on those platforms.

**Comment by DavidHuber-NOAA** [comment]
@KateFriedman-NOAA Sounds good, thanks for the update.  I will get these incorporated into my forks and continue testing.

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA One more commit at 5d98c64 to make it actually work now (hehe).

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA I just reverted changes in my branch to remove the `.x` from exec names and remove the "/install" bit in the `exec` and `ush` folder paths. Retesting branch now with new global-workflow job.

**Comment by DavidHuber-NOAA** [comment]
Noted, thanks @KateFriedman-NOAA.

**Comment by KateFriedman-NOAA** [comment]
@jack-woollen Please see the following for fit2obs and workflow updates I have made and tested.

### Package updates to Fit2Obs and global-workflow

I have:

1) made some updates in my fit2obs branch to accommodate significant script updates in global-workflow (e.g. changing fit2obs scripts to bash). Here is my fit2obs branch compared against Fit2Obs `develop`: https://github.com/NOAA-EMC/Fit2Obs/compare/develop...KateFriedman-NOAA:Fit2Obs:feature/wcoss2_jet_support
2) created a dedicated fit2obs job in global-workflow (instead of having it run within the vrfy job and self-submitting from it).  When running fit2obs via the dedicated job in global-workflow I do not use the `subfits*` scripts, I go straight to `batrun/excfs_gdas_vrfyfits.sh.ecf` after setting a few things via `config.fit2obs` and a new `jobs/JGDAS_FIT2OBS` JJOB script. Here is my global-workflow branch for adding dedicated fit2obs job compared against global-workflow `develop` to show changes: https://github.com/NOAA-EMC/global-workflow/compare/develop...KateFriedman-NOAA:global-workflow:feature/fit2obs

### Test outputs

Please ignore the first 4 cycles (spinup).

Hera:
* workflow job logs: /scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/testfit2obs/logs/*/gdasfit2obs.log
* fit2obs output:
  * /scratch1/NCEPDEV/global/Kate.Friedman/archive/testfit2obs/fits
  * /scratch1/NCEPDEV/global/Kate.Friedman/archive/testfit2obs/horiz/*

Orion:
* workflow job logs: /work/noaa/stmp/kfriedma/comrot/testfit2obs/logs/*/gdasfit2obs.log
* fit2obs output:
  * /work/noaa/global/kfriedma/archive/testfit2obs/fits
  * /work/noaa/global/kfriedma/archive/testfit2obs/horiz/*

WCOSS2:
* workflow job logs: /lfs/h2/emc/ptmp/kate.friedman/comrot/testfit2obs/logs/*/gdasfit2obs.log
* fit2obs output:
  * /lfs/h2/emc/global/noscrub/kate.friedman/archive/testfit2obs/fits
  * /lfs/h2/emc/global/noscrub/kate.friedman/archive/testfit2obs/horiz/*

---------------------------------------------------------

Please let me know if I have run the fit2obs package correctly from the new global-workflow fit2obs job. Also let me know if you have any questions about changes I made in my fit2obs branch. Thanks!

Notes:

1. I added the fit2obs job to global-workflow for every cycle but the first few cycles don't actually run it since needed inputs aren't yet available. The job checks for inputs and aborts if too early or fails if far enough in but inputs are missing.
2. I am running my tests on all three machines for another four cycles to check that it still works after updates to remove the `.x` from exec names and revert my fit2obs branch changes to include `/install` in exec and ush paths. Please keep this in mind if you look at my global-workflow logs.

Thanks!

**Comment by jack-woollen** [comment]
@KateFriedman-NOAA A couple things. I guess the workflow is only making forecasts at 00z. So that means at other hours it only makes fits for f00 and f06. Also since the vrfyarch only has forecasts up to f120, not f126, no fit files for f120 are made. Given that, I think its working ok!

**Comment by KateFriedman-NOAA** [comment]
Thanks @jack-woollen ! Yes, sorry, should have noted I only ran the gfs suite at 00z and only out to 120hrs (our current default length). I will submit a PR into Fit2Obs `develop` with my changes and then request a new tag.

**Comment by KateFriedman-NOAA** [comment]
@jack-woollen Would you mind cutting a new Fit2Obs tag now? We will have another update shortly but a tag now would help me wrap up some work on the global-workflow side to create a dedicated fit2obs job. Thanks!

**Comment by jack-woollen** [comment]
@KateFriedman-NOAA Not at all. Try wflow.1.0!

**Comment by KateFriedman-NOAA** [comment]
@jack-woollen That tag doesn't exist yet. I don't see it in the tag list in the repo and can't clone it.

**Comment by jack-woollen** [comment]
@KateFriedman-NOAA there now, needed to push it.

**Comment by KateFriedman-NOAA** [comment]
Got it, thanks @jack-woollen !
