### ISSUE TITLE
Build fit2obs w/ cmake

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/Fit2Obs#6]
As the GFS application is cmake compatible, fit2obs will need to be updated to be built w/ cmake.
I will use this issue to document the progress for that work.

@KateFriedman-NOAA @jack-woollen FYI.

**Comment by KateFriedman-NOAA** [comment]
Thanks @aerorahul ! This will help with work happening for issue #4 and https://github.com/NOAA-EMC/global-workflow/issues/1405.

**Comment by aerorahul** [comment]
This work is being performed in the branch https://github.com/NOAA-EMC/Fit2Obs/tree/feature/cmake

All executables were built successfully.
The executables have an extension `.x` consistent with all executables in the GFS application.

To build, a convenience script `ush/build.sh` is added similar to other components of the GFS. 
Usage:
```
./ush/build.sh
```
It detects the machine, loads the modules, builds the application and installs the artifacts.

I have not removed the deprecated, hand-written makefiles or shell scripts that drive the build.
I have also not updated the scripts to use the executables with the `.x` extension.

Both those activities will be deferred after the cmake build compatibility is merged.
